export const CountryAirportsList = [
  "ATL - Atlanta, United States",
  "PEK - Beijing, China",
  "LAX - Los Angeles, United States",
  "HND - Tokyo, Japan",
  "ORD - Chicago, United States",
  "DXB - Dubai, United Arab Emirates",
  "HKG - Hong Kong, Hong Kong",
  "LHR - London, United Kingdom",
  "CDG - Paris, France",
  "FRA - Frankfurt, Germany",
  "DFW - Dallas, United States",
  "PVG - Shanghai, China",
  "DEN - Denver, United States",
  "CGK - Jakarta, Indonesia",
  "AMS - Amsterdam, Netherlands",
  "CAN - Guangzhou, China",
  "SIN - Singapore, Singapore",
  "ICN - Seoul, South Korea",
  "SFO - San Francisco, United States",
  "MAD - Madrid, Spain",
  "IST - Istanbul, Turkey",
  "PHX - Phoenix, United States",
  "MIA - Miami, United States",
  "BKK - Bangkok, Thailand",
  "FCO - Rome, Italy",
  "KUL - Kuala Lumpur, Malaysia",
  "DEL - Delhi, India",
  "MCO - Orlando, United States",
  "LAS - Las Vegas, United States",
  "CTU - Chengdu, China",
  "JFK - New York, United States",
  "CLT - Charlotte, United States",
  "MUC - Munich, Germany",
  "BOM - Mumbai, India",
  "SEA - Seattle, United States",
  "MEL - Melbourne, Australia",
  "SYD - Sydney, Australia",
  "DUS - Dusseldorf, Germany",
  "PRG - Prague, Czechia",
  "BOS - Boston, United States",
  "BWI - Baltimore, United States",
  "MXP - Milan, Italy",
  "EWR - Newark, United States",
  "GRU - Sao Paulo, Brazil",
  "IAD - Washington, United States",
  "KIX - Osaka, Japan",
  "LGA - New York, United States",
  "MNL - Manila, Philippines",
  "SVO - Moscow, Russian Federation",
  "ZRH - Zurich, Switzerland",
  "MSP - Minneapolis, United States",
  "PHL - Philadelphia, United States",
];
